### ISSUE TITLE
Old beta food system

### ISSUE THREAD

**Issue by Simple205** [exaskye/Fabrication-Features#75] opened 2021-09-05 23:40 UTC
I would like to see a feature added that restores the old food system before beta 1.8 where food restores health instead of hunger. And this would automatically move the armor slot to where the hunger bar was.

**Comment by Cynosphere** [comment] 2021-09-06 00:02
Duplicate of #69

**Comment by Simple205** [comment] 2021-09-06 09:08
i didnt notice earlier my bad

**Closed as completed** 2021-09-06 09:08 UTC
Labels: Already Added
